### ISSUE TITLE
volunteers should be deployed on midburn-k8s environment 

### ISSUE THREAD

**Issue by shaytidhar** [Midburn/Volunteers#95]
## TODO
* upgrade to node 8 + yarn
* dockerize + docker-compose environment including mongo with support for import production DB data
* kubernitize in [The Midburn K8S Environment](https://github.com/Midburn/midburn-k8s)
* continuous deployment every commit to volunteers master to staging environment - staging-volunteers.midburn.org
* staging / production environments should start with empty DB, but should provide production DB export

**Comment by OriHoch** [comment]
done
